// <auto-generated />
using DeliverySave;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliverySave.Migrations
{
    [DbContext(typeof(DeliverySaveContext))]
    partial class DeliverySaveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("DeliverySave.Address", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("is_delivered")
                        .HasColumnType("TEXT");

                    b.Property<string>("is_picked")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("pid")
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
